data "azurerm_key_vault" "kv" {
  name                = var.key_vault_name
  resource_group_name = var.key_vault_rg_name
}

data "azurerm_key_vault_secret" "monitor_notification_slack_email" {
  name         = "monitor-notification-slack-email"
  key_vault_id = data.azurerm_key_vault.kv.id
}

data "azurerm_key_vault_secret" "monitor_notification_email" {
  name         = "monitor-notification-email"
  key_vault_id = data.azurerm_key_vault.kv.id
}

#
# Added new secrets
#
resource "random_password" "autogenerated_password_values" {
  count = length(var.keyvault_autogenerated_secrets)

  length           = 24
  special          = true
  override_special = "!$#%"
}

resource "azurerm_key_vault_secret" "autogenerated_secrets" {
  count = length(var.keyvault_autogenerated_secrets)

  name         = var.keyvault_autogenerated_secrets[count.index]
  value        = random_password.autogenerated_password_values[count.index].result
  key_vault_id = data.azurerm_key_vault.kv.id

  expiration_date = "2030-12-31T00:00:00Z"
  content_type    = "autogenerated-password"

  lifecycle {
    ignore_changes = [
      value,
    ]
  }
}

resource "azurerm_key_vault_secret" "raw_secrets" {

  for_each = { for secret in var.keyvault_raw_secrets : secret.name => secret }

  name         = each.value["name"]
  value        = each.value["value"]
  key_vault_id = data.azurerm_key_vault.kv.id

  expiration_date = "2022-12-31T00:00:00Z"
  content_type    = each.value["type"]
}
